//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mensajeria.UI.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class envio
    {
        public long id { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public decimal precio { get; set; }
        public Nullable<long> idRemitente { get; set; }
        public Nullable<long> idDireccionDestino { get; set; }
        public Nullable<long> idPaquete { get; set; }
        public Nullable<long> idEstado { get; set; }
        public Nullable<long> idTipoTransporte { get; set; }
    
        public virtual direccion direccion { get; set; }
        public virtual estadoEnvio estadoEnvio { get; set; }
        public virtual paquete paquete { get; set; }
        public virtual tipoTransporte tipoTransporte { get; set; }
        public virtual persona persona { get; set; }
    }
}
