//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mensajeria.UI.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MensajeriaBDEntities : DbContext
    {
        public MensajeriaBDEntities()
            : base("name=MensajeriaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bodega> bodega { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<envio> envio { get; set; }
        public virtual DbSet<estadoEnvio> estadoEnvio { get; set; }
        public virtual DbSet<historial> historial { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<oficina> oficina { get; set; }
        public virtual DbSet<paquete> paquete { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoTransporte> tipoTransporte { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<tipoDocumento> tipoDocumento { get; set; }
    }
}
